'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useRef, useState } from 'react';

const API = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001/api/v1';

type MatchPlayer = { registrationId:string; club:{organizationId:string;name:string}; fullName:string; firstName:string; lastName:string; birthDate?:string|null; federationId?:string|null; photoDataUrl?:string|null; shirtNumber?:number|null; license?:{number?:string|null;season:string;status:string}|null; eligibility:'ELIGIBLE'|'CHECK_REQUIRED' };
type MatchContext = { id:string; season:string; competition:string; homeClub:{id:string;name:string}; awayClub:{id:string;name:string} };
type PlayersResponse = { match:MatchContext; players:MatchPlayer[] };
type ResolveResponse = { matchContext:MatchContext; query:string; match:(MatchPlayer&{score?:number})|null; alternatives:Array<MatchPlayer&{score?:number}>; ambiguous:boolean };
type PlayerControl = { registrationId:string; clubId:string; status:string; controlledAt?:string|null; reason?:string|null; evidencePhotoDataUrl?:string|null; evidencePhotoSha256?:string|null };
type ControlSummary = { controls:PlayerControl[] };
type TranscriptionResponse = { text:string };

async function apiRequest<T>(path:string, token:string, init?:RequestInit):Promise<T>{
  const response=await fetch(`${API}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init?.headers??{})}});
  const payload=await response.json().catch(()=>({}));
  if(!response.ok){const raw=(payload as {message?:string|string[]}).message;throw new Error(Array.isArray(raw)?raw.join(' · '):raw??`Erreur ${response.status}`)}
  return payload as T;
}
function blobToDataUrl(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result??''));reader.onerror=()=>reject(new Error('Lecture impossible'));reader.readAsDataURL(blob)})}
function compressPhoto(file:File):Promise<string>{
  return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('Lecture de la photo impossible'));reader.onload=()=>{const image=new Image();image.onerror=()=>reject(new Error('Photo illisible'));image.onload=()=>{const max=1100;const scale=Math.min(1,max/Math.max(image.width,image.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));const ctx=canvas.getContext('2d');if(!ctx)return reject(new Error('Traitement photo impossible'));ctx.drawImage(image,0,0,canvas.width,canvas.height);resolve(canvas.toDataURL('image/jpeg',.78))};image.src=String(reader.result)};reader.readAsDataURL(file)})
}
const statusLabel:Record<string,string>={ISSUED_BY_FBF:'Délivrée par la FBF',APPROVED_BY_LEAGUE:'Validée par la Ligue',PENDING_FBF:'En attente FBF',REJECTED:'Rejetée'};

export function OfficialMatchPlayerControlGpt({token,matchId}:{token:string;matchId:string}){
  const [query,setQuery]=useState(''); const [selected,setSelected]=useState<MatchPlayer|null>(null); const [players,setPlayers]=useState<MatchPlayer[]>([]); const [matchContext,setMatchContext]=useState<MatchContext|null>(null); const [teamId,setTeamId]=useState(''); const [controls,setControls]=useState<Record<string,PlayerControl>>({});
  const [loading,setLoading]=useState(false); const [recording,setRecording]=useState(false); const [voiceBusy,setVoiceBusy]=useState(false); const [controlBusy,setControlBusy]=useState(false); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [anomalyOpen,setAnomalyOpen]=useState(false); const [anomalyReason,setAnomalyReason]=useState(''); const [evidencePhoto,setEvidencePhoto]=useState<string|null>(null); const [photoBusy,setPhotoBusy]=useState(false);
  const recorderRef=useRef<MediaRecorder|null>(null); const streamRef=useRef<MediaStream|null>(null); const chunksRef=useRef<Blob[]>([]); const photoInputRef=useRef<HTMLInputElement|null>(null);
  async function refreshControls(){const summary=await apiRequest<ControlSummary>(`/matches/${encodeURIComponent(matchId)}/sheet/player-controls`,token);setControls(Object.fromEntries(summary.controls.map(c=>[c.registrationId,c])))}
  useEffect(()=>{void apiRequest<PlayersResponse>(`/official-match-access/${encodeURIComponent(matchId)}/players`,token).then(async r=>{setPlayers(r.players??[]);setMatchContext(r.match);setTeamId(r.match.homeClub.id);await refreshControls()}).catch(e=>setError(e instanceof Error?e.message:'Chargement impossible'));return()=>streamRef.current?.getTracks().forEach(t=>t.stop())},[matchId,token]);
  const sheetPlayers=useMemo(()=>players.filter(p=>Boolean(controls[p.registrationId])),[players,controls]);
  const teamPlayers=useMemo(()=>sheetPlayers.filter(p=>p.club.organizationId===teamId).sort((a,b)=>(a.shirtNumber??999)-(b.shirtNumber??999)),[sheetPlayers,teamId]);
  const verifiedCount=teamPlayers.filter(p=>controls[p.registrationId]?.status==='VERIFIED').length; const anomalyCount=teamPlayers.filter(p=>controls[p.registrationId]?.status==='ANOMALY').length;

  async function resolve(text:string){const value=text.trim();if(!value)return;setLoading(true);setError('');try{const r=await apiRequest<ResolveResponse>(`/official-match-access/${encodeURIComponent(matchId)}/players/resolve?q=${encodeURIComponent(value)}`,token);const valid=r.match&&controls[r.match.registrationId]?r.match:null;const alts=r.alternatives.filter(c=>controls[c.registrationId]);const chosen=valid??(!valid&&alts.length===1?alts[0]:null);if(chosen){setSelected(chosen);setTeamId(chosen.club.organizationId)}else setError('Aucun joueur de la feuille ne correspond suffisamment à la dictée.')}catch(e){setError(e instanceof Error?e.message:'Recherche impossible')}finally{setLoading(false)}}
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();void resolve(query)}
  async function transcribeRecording(blob:Blob){setVoiceBusy(true);setError('');setMessage('Transcription GPT en cours…');try{const audioDataUrl=await blobToDataUrl(blob);const context=sheetPlayers.map(p=>`${p.fullName}, numéro ${p.shirtNumber??'inconnu'}, ${p.club.name}`).join(' ; ');const r=await apiRequest<TranscriptionResponse>('/official-assistant/transcriptions',token,{method:'POST',body:JSON.stringify({audioDataUrl,language:'fr',context})});const transcript=r.text?.trim();if(!transcript)throw new Error('La dictée n’a produit aucun texte.');setQuery(transcript);setMessage(`GPT a entendu : « ${transcript} »`);await resolve(transcript)}catch(e){setError(e instanceof Error?e.message:'Transcription GPT impossible')}finally{setVoiceBusy(false)}}
  async function toggleVoice(){if(recording){recorderRef.current?.stop();setRecording(false);return}if(voiceBusy)return;if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){setError('L’enregistrement audio n’est pas disponible.');return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});streamRef.current=stream;const preferred=['audio/mp4','audio/webm;codecs=opus','audio/webm'];const mimeType=preferred.find(t=>MediaRecorder.isTypeSupported(t));const recorder=mimeType?new MediaRecorder(stream,{mimeType}):new MediaRecorder(stream);recorderRef.current=recorder;chunksRef.current=[];recorder.ondataavailable=e=>{if(e.data.size>0)chunksRef.current.push(e.data)};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:recorder.mimeType||'audio/mp4'});stream.getTracks().forEach(t=>t.stop());streamRef.current=null;if(blob.size>0)void transcribeRecording(blob)};recorder.start();setRecording(true);setMessage('Parlez maintenant, puis touchez « Terminer »…')}catch{setError('Autorisez le microphone pour utiliser GPT-Transcribe.')}}
  function openPlayer(p:MatchPlayer){setSelected(p);setQuery(p.fullName);setTeamId(p.club.organizationId);setError('');setMessage('');setAnomalyOpen(false)}
  async function saveControl(p:MatchPlayer,status:'VERIFIED'|'ANOMALY',reason?:string,photo?:string|null){setControlBusy(true);setError('');setMessage('');try{await apiRequest(`/matches/${encodeURIComponent(matchId)}/sheet/players/${encodeURIComponent(p.registrationId)}/control`,token,{method:'POST',body:JSON.stringify({status,reason,evidencePhotoDataUrl:photo||undefined})});await refreshControls();setMessage(status==='VERIFIED'?`${p.fullName} a été vérifié.`:`Anomalie avec preuve enregistrée pour ${p.fullName}.`);setAnomalyOpen(false);setAnomalyReason('');setEvidencePhoto(null)}catch(e){setError(e instanceof Error?e.message:'Contrôle impossible')}finally{setControlBusy(false)}}
  function reportAnomaly(p:MatchPlayer){setSelected(p);setAnomalyReason(controls[p.registrationId]?.reason??'');setEvidencePhoto(null);setAnomalyOpen(true);setError('');setMessage('')}
  async function onPhoto(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;setPhotoBusy(true);setError('');try{const photo=await compressPhoto(file);setEvidencePhoto(photo)}catch(err){setError(err instanceof Error?err.message:'Photo impossible')}finally{setPhotoBusy(false)}}
  function confirmAnomaly(){if(!selected)return;if(!anomalyReason.trim()){setError('Indiquez le motif de l’anomalie.');return}if(!evidencePhoto){setError('Prenez une photo terrain avant de confirmer l’anomalie.');return}void saveControl(selected,'ANOMALY',anomalyReason.trim(),evidencePhoto)}
  const selectedControl=selected?controls[selected.registrationId]:undefined; const initials=selected?`${selected.firstName?.[0]??''}${selected.lastName?.[0]??''}`:'';

  return <section className="data-panel" style={{padding:20}}>
    <div style={{padding:'20px 22px',borderRadius:14,background:'#0b2c48',color:'#fff'}}><label style={{color:'#dfba54',fontSize:9,fontWeight:900,letterSpacing:'.13em'}}>AVANT-MATCH · CONTRÔLE OFFICIEL · GPT-TRANSCRIBE</label><h2 style={{margin:'7px 0 4px',fontSize:24}}>Appeler le joueur, afficher sa licence, contrôler</h2><p style={{margin:0,color:'#b8c6d1',fontSize:11}}>La dictée GPT retrouve le joueur. Toute anomalie peut être documentée par une photo terrain horodatée dans l’audit.</p></div>
    {matchContext&&<div style={{display:'flex',gap:8,marginTop:14,flexWrap:'wrap'}}>{[matchContext.homeClub,matchContext.awayClub].map(club=>{const cp=sheetPlayers.filter(p=>p.club.organizationId===club.id);const done=cp.filter(p=>controls[p.registrationId]?.status==='VERIFIED').length;const anomalies=cp.filter(p=>controls[p.registrationId]?.status==='ANOMALY').length;return <button key={club.id} type="button" onClick={()=>{setTeamId(club.id);setSelected(null)}} style={{padding:'10px 14px',border:teamId===club.id?'2px solid #d7af47':'1px solid #dce3e7',borderRadius:9,background:teamId===club.id?'#0b2c48':'#fff',color:teamId===club.id?'#fff':'#203147',fontWeight:900}}>{club.name} · {done}/{cp.length}{anomalies?` · ⚠ ${anomalies}`:''}</button>})}</div>}
    {teamPlayers.length>0&&<div style={{marginTop:14,padding:14,borderRadius:12,background:'#f7f9fa',display:'flex',justifyContent:'space-between'}}><strong>Progression du contrôle</strong><strong>{verifiedCount}/{teamPlayers.length} vérifiés{anomalyCount?` · ${anomalyCount} anomalie(s)`:''}</strong></div>}
    {error&&<div className="api-error">{error}</div>}{message&&<div className="success-message">{message}</div>}
    <form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'minmax(180px,1fr) auto auto',gap:8,alignItems:'end',marginTop:14,padding:14,border:'1px solid #e2e7ea',borderRadius:12,background:'#fff'}}><label style={{display:'grid',gap:6,color:'#596879',fontSize:10,fontWeight:800}}>Nom du joueur<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex. Rodrigue Hountondji" autoComplete="off" style={{width:'100%',padding:'10px 11px',border:'1px solid #dce3e7',borderRadius:8}}/></label><button type="submit" disabled={loading||voiceBusy} style={{padding:'10px 13px',border:0,borderRadius:8,background:'#d7af47',fontWeight:900}}>{loading?'…':'Rechercher'}</button><button type="button" onClick={()=>void toggleVoice()} disabled={voiceBusy} style={{padding:'10px 13px',border:0,borderRadius:8,background:recording?'#9e3933':'#0d3150',color:'#fff',fontWeight:900}}>{voiceBusy?'GPT…':recording?'■ Terminer':'🎤 Parler GPT'}</button></form>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,240px) minmax(0,1fr)',gap:16,marginTop:14}}><div style={{border:'1px solid #e2e7ea',borderRadius:12,overflow:'hidden',background:'#fff'}}><div style={{padding:'11px 13px',background:'#f7f9fa',color:'#596879',fontSize:10,fontWeight:900}}>JOUEURS DE LA FEUILLE</div>{teamPlayers.map(p=>{const c=controls[p.registrationId];const verified=c?.status==='VERIFIED';const anomaly=c?.status==='ANOMALY';return <button key={p.registrationId} type="button" onClick={()=>openPlayer(p)} style={{width:'100%',display:'grid',gridTemplateColumns:'38px 1fr auto',gap:9,alignItems:'center',padding:'10px 12px',border:0,borderBottom:'1px solid #edf0f2',background:selected?.registrationId===p.registrationId?'#f8f1dc':'#fff',textAlign:'left'}}><span style={{width:34,height:34,display:'grid',placeItems:'center',borderRadius:8,background:'#0b2c48',color:'#fff',fontWeight:900}}>#{p.shirtNumber??'—'}</span><span><strong style={{display:'block',color:'#203147',fontSize:11}}>{p.fullName}</strong><small style={{color:'#84909e'}}>{p.license?.number??'Licence à contrôler'}</small></span><span style={{color:anomaly?'#b33b35':verified?'#27704d':'#a3adb6',fontWeight:900}}>{anomaly?'⚠':verified?'✓':'○'}</span></button>})}</div>
      {selected?<section style={{padding:20,border:selectedControl?.status==='ANOMALY'?'1px solid #d66b64':'1px solid #e2e7ea',borderRadius:14,background:'#fff'}}><div style={{display:'grid',gridTemplateColumns:'150px minmax(0,1fr)',gap:22}}><div><div style={{width:145,height:172,borderRadius:12,overflow:'hidden',display:'grid',placeItems:'center',background:'#e8edf2',color:'#0b2c48',fontSize:38,fontWeight:900}}>{selected.photoDataUrl?<img src={selected.photoDataUrl} alt={selected.fullName} style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<span>{initials}</span>}</div></div><div><span style={{color:'#a37c22',fontSize:9,fontWeight:900}}>{selected.club.name}</span><h2 style={{margin:'5px 0',fontSize:27}}>{selected.fullName}</h2><strong style={{display:'inline-block',padding:'7px 11px',borderRadius:8,background:'#0b2c48',color:'#fff'}}>N° {selected.shirtNumber??'—'}</strong><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:9,marginTop:15}}>{[['Date de naissance',selected.birthDate?new Date(selected.birthDate).toLocaleDateString('fr-FR'):'—'],['Identifiant fédéral',selected.federationId??'—'],['N° licence',selected.license?.number??'—'],['Statut',selected.license?.status?statusLabel[selected.license.status]??selected.license.status:'Aucune licence']].map(([l,v])=><div key={l} style={{padding:11,borderRadius:9,background:'#f7f9fa'}}><small style={{display:'block',color:'#84909e',fontWeight:800}}>{l}</small><strong>{v}</strong></div>)}</div>{selectedControl?.status==='ANOMALY'&&<div style={{marginTop:12,padding:11,borderRadius:9,background:'#fae8e6',color:'#9e3933'}}><strong>⚠ Anomalie signalée</strong><div>{selectedControl.reason}</div>{selectedControl.evidencePhotoDataUrl&&<img src={selectedControl.evidencePhotoDataUrl} alt="Preuve terrain" style={{marginTop:9,maxWidth:180,maxHeight:150,borderRadius:8,objectFit:'cover'}}/>}</div>}<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:8,marginTop:16}}><button type="button" onClick={()=>void saveControl(selected,'VERIFIED')} disabled={controlBusy||selectedControl?.status==='VERIFIED'} style={{padding:13,border:0,borderRadius:9,background:'#d7af47',fontWeight:900}}>✓ Photo et licence contrôlées — Valider</button><button type="button" onClick={()=>reportAnomaly(selected)} disabled={controlBusy} style={{padding:'13px 15px',border:'1px solid #d66b64',borderRadius:9,background:'#fff',color:'#9e3933',fontWeight:900}}>⚠ Anomalie</button></div></div></div></section>:<div style={{display:'grid',placeItems:'center',minHeight:300,border:'1px dashed #dce3e7',borderRadius:14,color:'#84909e'}}><strong>Appelez un joueur ou utilisez « Parler GPT ».</strong></div>}
    </div>
    {anomalyOpen&&selected&&<div role="dialog" aria-modal="true" style={{position:'fixed',inset:0,zIndex:50,background:'rgba(4,18,31,.66)',display:'grid',placeItems:'center',padding:20}}><section style={{width:'min(620px,100%)',maxHeight:'90vh',overflow:'auto',background:'#fff',borderRadius:16,padding:22,boxShadow:'0 20px 60px rgba(0,0,0,.28)'}}><label style={{color:'#9e3933',fontSize:10,fontWeight:900}}>PREUVE D’ANOMALIE · {selected.club.name}</label><h2 style={{margin:'6px 0'}}>⚠ {selected.fullName} · N° {selected.shirtNumber??'—'}</h2><p style={{color:'#596879',fontSize:12}}>Décrivez le problème puis prenez une photo terrain. La décision reste celle de l’officiel et la preuve est tracée dans l’audit.</p><label style={{display:'grid',gap:6,fontWeight:800,fontSize:12}}>Motif<textarea value={anomalyReason} onChange={e=>setAnomalyReason(e.target.value)} maxLength={500} rows={3} placeholder="Ex. photo de licence ne correspondant pas au joueur présenté" style={{padding:11,border:'1px solid #dce3e7',borderRadius:9,resize:'vertical'}}/></label><input ref={photoInputRef} type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>void onPhoto(e)} style={{display:'none'}}/><div style={{marginTop:14,display:'grid',gridTemplateColumns:evidencePhoto?'180px 1fr':'1fr',gap:14,alignItems:'center'}}>{evidencePhoto&&<img src={evidencePhoto} alt="Photo terrain à confirmer" style={{width:180,height:150,objectFit:'cover',borderRadius:10,border:'1px solid #dce3e7'}}/>}<button type="button" onClick={()=>photoInputRef.current?.click()} disabled={photoBusy} style={{padding:14,border:'1px dashed #8aa0b2',borderRadius:10,background:'#f7f9fa',fontWeight:900}}>{photoBusy?'Traitement…':evidencePhoto?'📷 Reprendre la photo':'📷 Prendre la photo terrain'}</button></div>{evidencePhoto&&<div style={{marginTop:10,padding:10,borderRadius:9,background:'#e7f4ec',color:'#27704d',fontSize:11,fontWeight:800}}>✓ Photo capturée et compressée. Elle sera horodatée, liée au joueur et son empreinte SHA-256 sera conservée avec l’audit.</div>}<div style={{display:'flex',justifyContent:'flex-end',gap:8,marginTop:18}}><button type="button" onClick={()=>{setAnomalyOpen(false);setEvidencePhoto(null)}} disabled={controlBusy} style={{padding:'11px 15px'}}>Annuler</button><button type="button" onClick={confirmAnomaly} disabled={controlBusy||photoBusy||!anomalyReason.trim()||!evidencePhoto} style={{padding:'11px 15px',border:0,borderRadius:8,background:'#9e3933',color:'#fff',fontWeight:900}}>{controlBusy?'Enregistrement…':'⚠ Confirmer l’anomalie avec preuve'}</button></div></section></div>}
  </section>;
}
